language: node_js
node_js:
- '4.3'
before_script:
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: wparad@gmail.com
  api_key:
    secure: IPhN4q67hHexj+TRITo3xABL6hrHt6SJ2+FYC0HO+HILt3Qa9DV2C4NSl4a+2rEPC9AOKAH+9kHLYVDFGl67IPXn3njMIiWmbkMcTPDq8L7clS4PMA1LHSc0IL82+bWVcq4SaKA2rLYWiWczF+YLXaz4QPq5jvaKz4hSYoSaPwFdnzyCV3XsQH+7PXctzYQ39oZAOfsS8uR7KLueyBo4eYbkgE5Xm7FXFpEwjweNHNOQhUT8lya6HrKSnPbMdUU0Hg2BVbvryiQXvEqYuhs3Ac+1xg8Whl0O6duXsc/7EisFJcojSy1FykCbrQu5WsGBnIXMV5GFZpbKwpEthX3bUYONtjEEFxlOxEprH565oQ86u6wdzzuyqm2QdofbSebMssdxfz+X87GUeuXJYQLg074HUGgg3OFR0/C4bSDZptH6JNBBrSY3htkjDIztgwbHNSyroCZsXXUzk0upL38U5lh+6GIiYj2tOzuIe5EJkh0R18RxwIikGgG6a3fGL2f2Irx+kBPts/3XfYRfRHPJ6kUUZdFaoLuqctM71zKnjdlAaL4xLbbslJ6dk1tZ4qxzaed5mbuwViyOKiH0HtaZQfmbiZpeGu5gcvAP7ChsPt0OZlbqXybBG6kd6gjX8b4Cc1hQB3iifZu3+itHSvf/IUgdBMMbtO6LQ5aO1GJOvms=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: RRTNKNZ3KdZhZwf5Z29PDwr/lvOft0xojIrw3BaSSTNBjpFRaS+y1hieeSmtSrty6jZ72lYEWsqzdxINStQ+HeNOTCp/vggPa8iFNwYmaC7AfHezc4YlxPeCIdejFEsCTPqnnaQ/QdUTf5G176VmhnsK9oVFg+TbIIJWQrlFUaBIbzku+taH6ZLU1auhdHrFGflQGfaGz/MCC5lugcaQoE1zqYI7np9j/OX1cHJSIXqUY3VM9w8GiTEidfmaMOEXfATn8A61AbEEIn1nDR1Ik9bjFEmVORlA9IoICBcjNgR7NWW+nr9TSEl9aXyD+0ehHN9YJqx8Isl9G2JrvnY1gR6VUIDXCnvICu3XhlneY3cbtLBTPfAm0p7f2L2Gq0DT9Yt8A1QO65Evx5r64oMJwicycWjrChBHPHiIhqX0wOgl5H8YbA2oqGqrdAT0ZSwpSJ1RS/T2ctkwumJ0iV3w2nRnpodAYu9rlneNOtr49NGxheoGkZ7dctsyyynCW83IMGCZcxip1csxmb+XdRcc8AwyWPuSzv20X6tzpeGid9uW0W2rTRmP222FXc4d+qTFX2fQqKrDDB2MuOQVJdltWEABaEYMmnukv+1gc17xjhBsygZ5YNQTuCLMdjDKxaRefkNoPdjgxZWZwOjKxDjhR9qJc7xZqLmLUtKhUufY3bs=
